- name: "Playbook to create Routing table in VM HOST MACHINE"
  hosts: host_machine
  gather_facts: false
  become: yes
  tasks:
  - name: "Delete old manual routes if exist"
    shell: "ip route del {{ hostvars[item]['POD_CIDR'] }} via {{ item }} dev {{ VM_NETWORK_BRIDGE }}"
    with_items: "{{ groups['slaves'] }}"
    ignore_errors: yes
    
  - name: "Add new manual routes"
    shell: "ip route add {{ hostvars[item]['POD_CIDR'] }} via {{ item }} dev {{ VM_NETWORK_BRIDGE }}"
    with_items: "{{ groups['slaves'] }}"
    ignore_errors: yes  