- name: "Playbook to create Routing table in VM HOST MACHINE"
  hosts: host_machine
  gather_facts: false
  become: yes
  tasks:
  - name: "Delete old manual routes if exist"
    shell: "ip route del {{ hostvars[item]['POD_CIDR'] }} via {{ item }} dev {{ VM_NETWORK_BRIDGE }}"
    with_items: "{{ groups['slaves'] }}"
    ignore_errors: yes
    
  - name: "Add new manual routes"
    shell: "ip route add {{ hostvars[item]['POD_CIDR'] }} via {{ item }} dev {{ VM_NETWORK_BRIDGE }}"
    with_items: "{{ groups['slaves'] }}"
    ignore_errors: yes  

  - name: "To remove DNS related errors loading kernel module"
    shell: "modprobe br_netfilter"

  - name: "Create a file to correct DNS issue inside pods"
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"